<?php

namespace Database\Seeders;

use App\Models\Document;
use App\Models\DocumentVersion;
use App\Models\Folder;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class DemoDataSeeder extends Seeder
{
    public function run(): void
    {
        Storage::disk('private')->makeDirectory('documents');

        $admin = User::query()->firstOrCreate(
            ['email' => 'admin@docbox.local'],
            ['name' => 'Admin', 'password' => 'Admin12345', 'role' => 'admin']
        );

        $users = User::factory()->count(5)->create();

        foreach ($users as $user) {
            $folder = Folder::query()->create([
                'owner_id' => $user->id,
                'name' => 'General',
            ]);

            for ($i = 1; $i <= 2; $i++) {
                $content = "Demo file {$i} for {$user->email}";
                $filename = Str::uuid()->toString().'.txt';
                $path = "documents/{$user->id}/{$filename}";
                Storage::disk('private')->put($path, $content);

                $document = Document::query()->create([
                    'owner_id' => $user->id,
                    'folder_id' => $folder->id,
                    'title' => "Demo document {$i}",
                    'description' => 'Generated by DemoDataSeeder',
                    'path' => $path,
                    'mime_type' => 'text/plain',
                    'size' => strlen($content),
                    'is_archived' => false,
                    'is_starred' => $i % 2 === 0,
                ]);

                $version = DocumentVersion::query()->create([
                    'document_id' => $document->id,
                    'version_number' => 1,
                    'path' => $path,
                    'mime_type' => 'text/plain',
                    'size' => strlen($content),
                    'checksum' => hash('sha256', $content),
                    'uploaded_by' => $user->id,
                ]);

                $document->update(['current_version_id' => $version->id]);
            }
        }

        $admin->sharedDocuments()->syncWithoutDetaching(
            Document::query()->inRandomOrder()->limit(3)->pluck('id')->mapWithKeys(fn ($id) => [$id => ['permission' => 'view']])->all()
        );
    }
}
